### PR TITLE
dotnet-svcutil: add escaped prefix to types named with specific keywords

### LINKED ISSUE #5488: dotnet-svcutil generated C# type names are missing `@` prefix when name is C# keyword too
**Describe the bug**
When WSDL contains complex type named `file` the dotnet-svcutil generates `public partial class file { ...`, which won't compile as the `file` is C# keyword.

**To Reproduce**
WSDL example for dotnet-svcutil tool with complex type named `file`:
```
<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:tns="http://www.example.org/" targetNamespace="http://www.example.org/">
  <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.example.org/" elementFormDefault="qualified">
      <xs:element name="file">
        <xs:complexType>
        </xs:complexType>
      </xs:element>
      <xs:element name="ConversionRateResponse">
      </xs:element>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="ConversionRateRequestMessage">
    <wsdl:part name="parameters" element="tns:file"/>
  </wsdl:message>
  <wsdl:portType name="CurrencyConverterPortType">
    <wsdl:operation name="GetConversionRate">
      <wsdl:input message="tns:ConversionRateRequestMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CurrencyConverterBinding" type="tns:CurrencyConverterPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetConversionRate">
      <soap:operation soapAction="http://www.example.org/GetConversionRate"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CurrencyConverterService">
    <wsdl:port name="CurrencyConverterPort" binding="tns:CurrencyConverterBinding">
      <soap:address location="http://www.example.org/currencyconverter"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
```

**Expected behavior**
Any `dotnet-svcutil` generated C# type/class name which conflicts with C# keyword should prefixed with `@`.
In case of provided WSDL it should correctly be `public partial class **@**file { ...`.

### PR DESCRIPTION
**Pull request by imcarolwang**
Fix #5488 and add test.

### CODE REVIEW

File: src/dotnet-svcutil/lib/src/CodeDomFixup/CodeDomVisitors/CodeTypeNameFixer.cs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+        {
+            foreach (CodeNamespace ns in cu.Namespaces)
+            {
+                foreach (CodeTypeDeclaration typeDeclaration in ns.Types)
+                {
+                    if(_reservedKeyword.Contains(typeDeclaration.Name))
+                    {
+                        typeDeclaration.Name = "@" + typeDeclaration.Name;
+                    }
+                }
```
Comment (HongGit) [inline src/dotnet-svcutil/lib/src/CodeDomFixup/CodeDomVisitors/CodeTypeNameFixer.cs:25]: It seems that this search path is only one level, not complete.

Comment (imcarolwang) [reply src/dotnet-svcutil/lib/src/CodeDomFixup/CodeDomVisitors/CodeTypeNameFixer.cs:40]: You’re right, the initial implementation didn’t account for nested contract types. I’ve updated the code and the tests to address this issue.
